version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=jatin
      - MONGO_PASSWORD=mongopass
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    command: npm run dev